"""3.12.1

Revision ID: 055f60b60f6e
Revises: a90eb1f0112e
Create Date: 2025-07-12 16:27:49.060543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '055f60b60f6e'
down_revision = 'a90eb1f0112e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sse_market',
    sa.Column('date', sa.String(length=10), nullable=False, comment='统计日期'),
    sa.Column('total_stocks', sa.Integer(), nullable=False, comment='上市股票数'),
    sa.Column('total_market_value', sa.Float(), nullable=False, comment='总市值（亿元）'),
    sa.Column('circulating_market_value', sa.Float(), nullable=False, comment='流通市值（亿元）'),
    sa.Column('total_share_capital', sa.Float(), nullable=False, comment='总股本（亿股）'),
    sa.Column('circulating_share_capital', sa.Float(), nullable=False, comment='流通股本（亿股）'),
    sa.Column('average_pe_ratio', sa.Float(), nullable=False, comment='平均市盈率'),
    sa.Column('turnover_rate', sa.Float(), nullable=False, comment='换手率（%）'),
    sa.Column('main_board_stocks', sa.Integer(), nullable=False, comment='主板股票数'),
    sa.Column('sci_tech_board_stocks', sa.Integer(), nullable=False, comment='科创板股票数'),
    sa.Column('main_board_market_value', sa.Float(), nullable=False, comment='主板市值（亿元）'),
    sa.Column('sci_tech_board_market_value', sa.Float(), nullable=False, comment='科创板市值（亿元）'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='上海证券交易所市场总貌表'
    )
    op.create_index(op.f('ix_data_sse_market_date'), 'data_sse_market', ['date'], unique=False)
    op.create_table('data_stock_tick',
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('trade_time', sa.String(length=19), nullable=False, comment='交易时间，格式：YYYY-MM-DD HH:MM:SS'),
    sa.Column('price', sa.Float(), nullable=False, comment='成交价格'),
    sa.Column('volume', sa.Integer(), nullable=False, comment='成交量（手）'),
    sa.Column('amount', sa.Float(), nullable=False, comment='成交额（元）'),
    sa.Column('direction', sa.String(length=10), nullable=False, comment='交易方向：买盘、卖盘、中性盘'),
    sa.Column('price_change', sa.Float(), nullable=True, comment='价格变动'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='股票分笔数据表'
    )
    op.create_index(op.f('ix_data_stock_tick_symbol'), 'data_stock_tick', ['symbol'], unique=False)
    op.create_index(op.f('ix_data_stock_tick_trade_time'), 'data_stock_tick', ['trade_time'], unique=False)
    op.create_table('data_szse_market',
    sa.Column('date', sa.String(length=10), nullable=False, comment='统计日期'),
    sa.Column('total_stocks', sa.Integer(), nullable=False, comment='上市股票数'),
    sa.Column('total_market_value', sa.Float(), nullable=False, comment='总市值（亿元）'),
    sa.Column('circulating_market_value', sa.Float(), nullable=False, comment='流通市值（亿元）'),
    sa.Column('turnover_rate', sa.Float(), nullable=False, comment='换手率（%）'),
    sa.Column('main_board_a_stocks', sa.Integer(), nullable=False, comment='主板A股数量'),
    sa.Column('main_board_b_stocks', sa.Integer(), nullable=False, comment='主板B股数量'),
    sa.Column('sme_board_stocks', sa.Integer(), nullable=False, comment='中小板股票数'),
    sa.Column('gem_board_stocks', sa.Integer(), nullable=False, comment='创业板股票数'),
    sa.Column('main_board_a_market_value', sa.Float(), nullable=False, comment='主板A股市值（亿元）'),
    sa.Column('main_board_b_market_value', sa.Float(), nullable=False, comment='主板B股市值（亿元）'),
    sa.Column('sme_board_market_value', sa.Float(), nullable=False, comment='中小板市值（亿元）'),
    sa.Column('gem_board_market_value', sa.Float(), nullable=False, comment='创业板市值（亿元）'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='深圳证券交易所市场总貌表'
    )
    op.create_index(op.f('ix_data_szse_market_date'), 'data_szse_market', ['date'], unique=False)
    op.alter_column('auth_dept', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_dept', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_menu', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_menu', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_role', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_role', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_user', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_user', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.add_column('data_stock_daily', sa.Column('pre_close', sa.Float(), nullable=True, comment='前收盘价'))
    op.add_column('data_stock_daily', sa.Column('adjust_flag', sa.String(length=10), nullable=True, comment='复权类型：不复权、前复权、后复权'))
    op.alter_column('data_stock_daily', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('data_stock_daily', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.add_column('data_stock_info', sa.Column('pe_ratio', sa.Float(), nullable=True, comment='市盈率'))
    op.add_column('data_stock_info', sa.Column('pb_ratio', sa.Float(), nullable=True, comment='市净率'))
    op.add_column('data_stock_info', sa.Column('total_market_value', sa.Float(), nullable=True, comment='总市值（元）'))
    op.add_column('data_stock_info', sa.Column('circulating_market_value', sa.Float(), nullable=True, comment='流通市值（元）'))
    op.add_column('data_stock_info', sa.Column('chairman', sa.String(length=50), nullable=True, comment='董事长'))
    op.add_column('data_stock_info', sa.Column('legal_representative', sa.String(length=50), nullable=True, comment='法定代表人'))
    op.add_column('data_stock_info', sa.Column('general_manager', sa.String(length=50), nullable=True, comment='总经理'))
    op.add_column('data_stock_info', sa.Column('secretary', sa.String(length=50), nullable=True, comment='董秘'))
    op.add_column('data_stock_info', sa.Column('registered_capital', sa.Float(), nullable=True, comment='注册资本'))
    op.add_column('data_stock_info', sa.Column('established_date', sa.String(length=10), nullable=True, comment='成立日期'))
    op.add_column('data_stock_info', sa.Column('website', sa.String(length=100), nullable=True, comment='公司网站'))
    op.add_column('data_stock_info', sa.Column('email', sa.String(length=100), nullable=True, comment='公司邮箱'))
    op.add_column('data_stock_info', sa.Column('office_address', sa.String(length=200), nullable=True, comment='办公地址'))
    op.add_column('data_stock_info', sa.Column('business_scope', sa.String(length=1000), nullable=True, comment='经营范围'))
    op.add_column('data_stock_info', sa.Column('company_profile', sa.String(length=2000), nullable=True, comment='公司简介'))
    op.alter_column('data_stock_info', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('data_stock_info', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.add_column('data_stock_minute', sa.Column('avg_price', sa.Float(), nullable=True, comment='均价'))
    op.add_column('data_stock_minute', sa.Column('adjust_flag', sa.String(length=10), nullable=True, comment='复权类型：不复权、前复权、后复权'))
    op.alter_column('data_stock_minute', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('data_stock_minute', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('help_issue', 'category_id',
               existing_type=mysql.INTEGER(),
               comment=None,
               existing_comment='类别',
               existing_nullable=False)
    op.alter_column('help_issue', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('help_issue', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('help_issue_category', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('help_issue_category', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('record_login', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('record_login', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('record_sms_send', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('record_sms_send', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('resource_images', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('resource_images', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('system_dict_details', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('system_dict_details', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('system_dict_type', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('system_dict_type', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('system_settings', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('system_settings', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('system_settings_tab', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('system_settings_tab', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings_tab', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('system_settings_tab', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('system_settings', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('system_settings', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('system_dict_type', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('system_dict_type', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('system_dict_details', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('system_dict_details', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('resource_images', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('resource_images', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('record_sms_send', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('record_sms_send', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('record_login', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('record_login', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('help_issue_category', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('help_issue_category', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('help_issue', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('help_issue', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('help_issue', 'category_id',
               existing_type=mysql.INTEGER(),
               comment='类别',
               existing_nullable=False)
    op.alter_column('data_stock_minute', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('data_stock_minute', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_column('data_stock_minute', 'adjust_flag')
    op.drop_column('data_stock_minute', 'avg_price')
    op.alter_column('data_stock_info', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('data_stock_info', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_column('data_stock_info', 'company_profile')
    op.drop_column('data_stock_info', 'business_scope')
    op.drop_column('data_stock_info', 'office_address')
    op.drop_column('data_stock_info', 'email')
    op.drop_column('data_stock_info', 'website')
    op.drop_column('data_stock_info', 'established_date')
    op.drop_column('data_stock_info', 'registered_capital')
    op.drop_column('data_stock_info', 'secretary')
    op.drop_column('data_stock_info', 'general_manager')
    op.drop_column('data_stock_info', 'legal_representative')
    op.drop_column('data_stock_info', 'chairman')
    op.drop_column('data_stock_info', 'circulating_market_value')
    op.drop_column('data_stock_info', 'total_market_value')
    op.drop_column('data_stock_info', 'pb_ratio')
    op.drop_column('data_stock_info', 'pe_ratio')
    op.alter_column('data_stock_daily', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('data_stock_daily', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_column('data_stock_daily', 'adjust_flag')
    op.drop_column('data_stock_daily', 'pre_close')
    op.alter_column('auth_user', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_user', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_role', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_role', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_menu', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_menu', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_dept', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_dept', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_data_szse_market_date'), table_name='data_szse_market')
    op.drop_table('data_szse_market')
    op.drop_index(op.f('ix_data_stock_tick_trade_time'), table_name='data_stock_tick')
    op.drop_index(op.f('ix_data_stock_tick_symbol'), table_name='data_stock_tick')
    op.drop_table('data_stock_tick')
    op.drop_index(op.f('ix_data_sse_market_date'), table_name='data_sse_market')
    op.drop_table('data_sse_market')
    # ### end Alembic commands ###
