"""3.12.1

Revision ID: 1e6e78c3854e
Revises: aec7a1fe7c16
Create Date: 2025-07-11 22:57:33.702246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6e78c3854e'
down_revision = 'aec7a1fe7c16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
