"""3.12.1

Revision ID: 890479036310
Revises: ae6392ba02e8
Create Date: 2025-07-11 23:12:17.675434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '890479036310'
down_revision = 'ae6392ba02e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_menu',
    sa.Column('title', sa.String(length=50), nullable=False, comment='名称'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='菜单图标'),
    sa.Column('redirect', sa.String(length=100), nullable=True, comment='重定向地址'),
    sa.Column('component', sa.String(length=255), nullable=True, comment='前端组件地址'),
    sa.Column('path', sa.String(length=50), nullable=True, comment='前端路由地址'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='是否禁用'),
    sa.Column('hidden', sa.Boolean(), nullable=False, comment='是否隐藏'),
    sa.Column('order', sa.Integer(), nullable=False, comment='排序'),
    sa.Column('menu_type', sa.String(length=8), nullable=False, comment='菜单类型'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='父菜单'),
    sa.Column('perms', sa.String(length=50), nullable=True, comment='权限标识'),
    sa.Column('noCache', sa.Boolean(), nullable=False, comment='如果设置为true，则不会被 <keep-alive> 缓存(默认 false)'),
    sa.Column('breadcrumb', sa.Boolean(), nullable=False, comment='如果设置为false，则不会在breadcrumb面包屑中显示(默认 true)'),
    sa.Column('affix', sa.Boolean(), nullable=False, comment='如果设置为true，则会一直固定在tag项中(默认 false)'),
    sa.Column('noTagsView', sa.Boolean(), nullable=False, comment='如果设置为true，则不会出现在tag中(默认 false)'),
    sa.Column('canTo', sa.Boolean(), nullable=False, comment='设置为true即使hidden为true，也依然可以进行路由跳转(默认 false)'),
    sa.Column('alwaysShow', sa.Boolean(), nullable=False, comment='\n            当你一个路由下面的 children 声明的路由大于1个时，自动会变成嵌套的模式，\n            只有一个时，会将那个子路由当做根路由显示在侧边栏，若你想不管路由下面的 children 声明的个数都显示你的根路由，\n            你可以设置 alwaysShow: true，这样它就会忽略之前定义的规则，一直显示根路由(默认 true)\n        '),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['auth_menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表'
    )
    op.create_index(op.f('ix_auth_menu_perms'), 'auth_menu', ['perms'], unique=False)
    op.create_table('record_login',
    sa.Column('telephone', sa.String(length=255), nullable=False, comment='手机号'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='是否登录成功'),
    sa.Column('platform', sa.String(length=8), nullable=False, comment='登陆平台'),
    sa.Column('login_method', sa.String(length=8), nullable=False, comment='认证方式'),
    sa.Column('ip', sa.String(length=50), nullable=True, comment='登陆地址'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='登陆地点'),
    sa.Column('country', sa.String(length=255), nullable=True, comment='国家'),
    sa.Column('province', sa.String(length=255), nullable=True, comment='县'),
    sa.Column('city', sa.String(length=255), nullable=True, comment='城市'),
    sa.Column('county', sa.String(length=255), nullable=True, comment='区/县'),
    sa.Column('operator', sa.String(length=255), nullable=True, comment='运营商'),
    sa.Column('postal_code', sa.String(length=255), nullable=True, comment='邮政编码'),
    sa.Column('area_code', sa.String(length=255), nullable=True, comment='地区区号'),
    sa.Column('browser', sa.String(length=50), nullable=True, comment='浏览器'),
    sa.Column('system', sa.String(length=50), nullable=True, comment='操作系统'),
    sa.Column('response', sa.Text(), nullable=True, comment='响应信息'),
    sa.Column('request', sa.Text(), nullable=True, comment='请求信息'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录记录表'
    )
    op.create_index(op.f('ix_record_login_telephone'), 'record_login', ['telephone'], unique=False)
    op.create_table('system_dict_type',
    sa.Column('dict_name', sa.String(length=50), nullable=False, comment='字典名称'),
    sa.Column('dict_type', sa.String(length=50), nullable=False, comment='字典类型'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='字典状态，是否禁用'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典类型表'
    )
    op.create_index(op.f('ix_system_dict_type_dict_name'), 'system_dict_type', ['dict_name'], unique=False)
    op.create_index(op.f('ix_system_dict_type_dict_type'), 'system_dict_type', ['dict_type'], unique=False)
    op.create_table('system_settings_tab',
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('classify', sa.String(length=255), nullable=False, comment='分类键'),
    sa.Column('tab_label', sa.String(length=255), nullable=False, comment='tab标题'),
    sa.Column('tab_name', sa.String(length=255), nullable=False, comment='tab标识符'),
    sa.Column('hidden', sa.Boolean(), nullable=False, comment='是否隐藏'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='是否禁用'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置分类表'
    )
    op.create_index(op.f('ix_system_settings_tab_classify'), 'system_settings_tab', ['classify'], unique=False)
    op.create_index(op.f('ix_system_settings_tab_tab_name'), 'system_settings_tab', ['tab_name'], unique=True)
    op.create_table('auth_role_menus',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['auth_menu.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ondelete='CASCADE')
    )
    op.create_table('auth_user_depts',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['auth_dept.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE')
    )
    op.create_table('auth_user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE')
    )
    op.create_table('help_issue_category',
    sa.Column('name', sa.String(length=50), nullable=False, comment='类别名称'),
    sa.Column('platform', sa.String(length=8), nullable=False, comment='展示平台'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可见'),
    sa.Column('create_user_id', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['create_user_id'], ['auth_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='常见问题类别表'
    )
    op.create_index(op.f('ix_help_issue_category_name'), 'help_issue_category', ['name'], unique=False)
    op.create_index(op.f('ix_help_issue_category_platform'), 'help_issue_category', ['platform'], unique=False)
    op.create_table('system_dict_details',
    sa.Column('label', sa.String(length=50), nullable=False, comment='字典标签'),
    sa.Column('value', sa.String(length=50), nullable=False, comment='字典键值'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='字典状态，是否禁用'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否默认'),
    sa.Column('order', sa.Integer(), nullable=False, comment='字典排序'),
    sa.Column('dict_type_id', sa.Integer(), nullable=False, comment='关联字典类型'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['dict_type_id'], ['system_dict_type.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='字典详情表'
    )
    op.create_index(op.f('ix_system_dict_details_label'), 'system_dict_details', ['label'], unique=False)
    op.create_index(op.f('ix_system_dict_details_value'), 'system_dict_details', ['value'], unique=False)
    op.create_table('system_settings',
    sa.Column('config_label', sa.String(length=255), nullable=False, comment='配置表标签'),
    sa.Column('config_key', sa.String(length=255), nullable=False, comment='配置表键'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置表内容'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注信息'),
    sa.Column('disabled', sa.Boolean(), nullable=False, comment='是否禁用'),
    sa.Column('tab_id', sa.Integer(), nullable=False, comment='关联tab标签'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['tab_id'], ['system_settings_tab.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置表'
    )
    op.create_index(op.f('ix_system_settings_config_key'), 'system_settings', ['config_key'], unique=True)
    op.create_table('help_issue',
    sa.Column('category_id', sa.Integer(), nullable=False, comment='类别'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('view_number', sa.Integer(), nullable=False, comment='查看次数'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否可见'),
    sa.Column('create_user_id', sa.Integer(), nullable=False, comment='创建人'),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('create_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', sa.DateTime(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', sa.Boolean(), nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['category_id'], ['help_issue_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['create_user_id'], ['auth_user.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='常见问题记录表'
    )
    op.create_index(op.f('ix_help_issue_title'), 'help_issue', ['title'], unique=False)
    op.alter_column('auth_dept', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_dept', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_auth_dept_dept_key'), 'auth_dept', ['dept_key'], unique=False)
    op.create_index(op.f('ix_auth_dept_name'), 'auth_dept', ['name'], unique=False)
    op.alter_column('auth_role', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_role', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_user', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_user', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_auth_user_name'), 'auth_user', ['name'], unique=False)
    op.create_index(op.f('ix_auth_user_telephone'), 'auth_user', ['telephone'], unique=False)
    op.alter_column('data_stock_daily', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('data_stock_daily', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_index('idx_symbol_date', table_name='data_stock_daily')
    op.alter_column('data_stock_info', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('data_stock_info', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_index('idx_symbol', table_name='data_stock_info')
    op.alter_column('data_stock_market', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('data_stock_market', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_index('idx_market_date', table_name='data_stock_market')
    op.alter_column('data_stock_minute', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('data_stock_minute', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_index('idx_symbol_time_period', table_name='data_stock_minute')
    op.alter_column('record_sms_send', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('record_sms_send', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('resource_images', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('resource_images', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resource_images', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('resource_images', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('record_sms_send', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('record_sms_send', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.create_index('idx_symbol_time_period', 'data_stock_minute', ['symbol', 'trade_time', 'period'], unique=True)
    op.alter_column('data_stock_minute', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('data_stock_minute', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.create_index('idx_market_date', 'data_stock_market', ['market', 'date'], unique=False)
    op.alter_column('data_stock_market', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('data_stock_market', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.create_index('idx_symbol', 'data_stock_info', ['symbol'], unique=True)
    op.alter_column('data_stock_info', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('data_stock_info', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.create_index('idx_symbol_date', 'data_stock_daily', ['symbol', 'trade_date'], unique=True)
    op.alter_column('data_stock_daily', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('data_stock_daily', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_auth_user_telephone'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_name'), table_name='auth_user')
    op.alter_column('auth_user', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_user', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('auth_role', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_role', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_auth_dept_name'), table_name='auth_dept')
    op.drop_index(op.f('ix_auth_dept_dept_key'), table_name='auth_dept')
    op.alter_column('auth_dept', 'update_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('auth_dept', 'create_datetime',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.drop_index(op.f('ix_help_issue_title'), table_name='help_issue')
    op.drop_table('help_issue')
    op.drop_index(op.f('ix_system_settings_config_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_system_dict_details_value'), table_name='system_dict_details')
    op.drop_index(op.f('ix_system_dict_details_label'), table_name='system_dict_details')
    op.drop_table('system_dict_details')
    op.drop_index(op.f('ix_help_issue_category_platform'), table_name='help_issue_category')
    op.drop_index(op.f('ix_help_issue_category_name'), table_name='help_issue_category')
    op.drop_table('help_issue_category')
    op.drop_table('auth_user_roles')
    op.drop_table('auth_user_depts')
    op.drop_table('auth_role_menus')
    op.drop_index(op.f('ix_system_settings_tab_tab_name'), table_name='system_settings_tab')
    op.drop_index(op.f('ix_system_settings_tab_classify'), table_name='system_settings_tab')
    op.drop_table('system_settings_tab')
    op.drop_index(op.f('ix_system_dict_type_dict_type'), table_name='system_dict_type')
    op.drop_index(op.f('ix_system_dict_type_dict_name'), table_name='system_dict_type')
    op.drop_table('system_dict_type')
    op.drop_index(op.f('ix_record_login_telephone'), table_name='record_login')
    op.drop_table('record_login')
    op.drop_index(op.f('ix_auth_menu_perms'), table_name='auth_menu')
    op.drop_table('auth_menu')
    # ### end Alembic commands ###
