"""3.12.1

Revision ID: aec7a1fe7c16
Revises: a3c6e62b4d73
Create Date: 2025-07-11 22:56:51.346453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec7a1fe7c16'
down_revision = 'a3c6e62b4d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
