"""3.12.1

Revision ID: bbe954ea8be3
Revises: 668e727e352a
Create Date: 2025-07-11 22:52:16.020494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbe954ea8be3'
down_revision = '668e727e352a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_auth_dept_dept_key', table_name='auth_dept')
    op.drop_index('ix_auth_dept_name', table_name='auth_dept')
    op.drop_table('auth_dept')
    op.drop_table('resource_images')
    op.drop_table('auth_user')
    op.drop_table('record_sms_send')
    op.drop_table('auth_role_depts')
    op.drop_index('ix_auth_role_name', table_name='auth_role')
    op.drop_index('ix_auth_role_role_key', table_name='auth_role')
    op.drop_table('auth_role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_role',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='名称'),
    sa.Column('role_key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='权限字符'),
    sa.Column('data_range', mysql.INTEGER(), autoincrement=False, nullable=False, comment='数据权限范围'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('desc', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='描述'),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否为超级角色'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='角色表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_auth_role_role_key', 'auth_role', ['role_key'], unique=False)
    op.create_index('ix_auth_role_name', 'auth_role', ['name'], unique=False)
    op.create_table('auth_role_depts',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['auth_dept.id'], name='auth_role_depts_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], name='auth_role_depts_ibfk_2', ondelete='CASCADE'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('record_sms_send',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='操作人'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='发送状态'),
    sa.Column('content', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='发送内容'),
    sa.Column('telephone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=11), nullable=False, comment='目标手机号'),
    sa.Column('desc', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='失败描述'),
    sa.Column('scene', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='发送场景'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='record_sms_send_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='短信发送记录表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='短信发送记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_user',
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=True, comment='头像'),
    sa.Column('telephone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=11), nullable=False, comment='手机号'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='邮箱地址'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='姓名'),
    sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='昵称'),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='密码'),
    sa.Column('gender', mysql.VARCHAR(collation='utf8mb4_general_ci', length=8), nullable=True, comment='性别'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否可用'),
    sa.Column('is_reset_password', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已经重置密码，没有重置的，登陆系统后必须重置密码'),
    sa.Column('last_ip', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='最后一次登录IP'),
    sa.Column('last_login', mysql.DATETIME(), nullable=True, comment='最近一次登录时间'),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否为工作人员'),
    sa.Column('wx_server_openid', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='服务端微信平台openid'),
    sa.Column('is_wx_server_openid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已有服务端微信平台openid'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='用户表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resource_images',
    sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='原图片名称'),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=False, comment='图片链接'),
    sa.Column('create_user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['create_user_id'], ['auth_user.id'], name='resource_images_ibfk_1', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='图片素材表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='图片素材表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_dept',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='部门名称'),
    sa.Column('dept_key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='部门标识'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True, comment='显示排序'),
    sa.Column('desc', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='描述'),
    sa.Column('owner', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='负责人'),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='联系电话'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='邮箱'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='上级部门'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['auth_dept.id'], name='auth_dept_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='部门表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='部门表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_auth_dept_name', 'auth_dept', ['name'], unique=False)
    op.create_index('ix_auth_dept_dept_key', 'auth_dept', ['dept_key'], unique=False)
    # ### end Alembic commands ###
