"""3.12.1

Revision ID: c4b3b1428842
Revises: 6950c846c74f
Create Date: 2025-07-11 22:50:13.404944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4b3b1428842'
down_revision = '6950c846c74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_user_depts')
    op.drop_table('auth_role_menus')
    op.drop_table('auth_user_roles')
    op.drop_index('ix_help_issue_title', table_name='help_issue')
    op.drop_table('help_issue')
    op.drop_index('ix_auth_menu_perms', table_name='auth_menu')
    op.drop_table('auth_menu')
    op.drop_index('ix_record_login_telephone', table_name='record_login')
    op.drop_table('record_login')
    op.drop_index('ix_system_settings_tab_classify', table_name='system_settings_tab')
    op.drop_index('ix_system_settings_tab_tab_name', table_name='system_settings_tab')
    op.drop_table('system_settings_tab')
    op.drop_index('ix_auth_role_name', table_name='auth_role')
    op.drop_index('ix_auth_role_role_key', table_name='auth_role')
    op.drop_table('auth_role')
    op.drop_index('ix_system_settings_config_key', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_table('resource_images')
    op.drop_table('auth_role_depts')
    op.drop_index('ix_auth_dept_dept_key', table_name='auth_dept')
    op.drop_index('ix_auth_dept_name', table_name='auth_dept')
    op.drop_table('auth_dept')
    op.drop_index('ix_auth_user_name', table_name='auth_user')
    op.drop_index('ix_auth_user_telephone', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('record_sms_send')
    op.drop_index('ix_help_issue_category_name', table_name='help_issue_category')
    op.drop_index('ix_help_issue_category_platform', table_name='help_issue_category')
    op.drop_table('help_issue_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help_issue_category',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='类别名称'),
    sa.Column('platform', mysql.VARCHAR(collation='utf8mb4_general_ci', length=8), nullable=False, comment='展示平台'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否可见'),
    sa.Column('create_user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['create_user_id'], ['auth_user.id'], name='help_issue_category_ibfk_1', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='常见问题类别表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='常见问题类别表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_help_issue_category_platform', 'help_issue_category', ['platform'], unique=False)
    op.create_index('ix_help_issue_category_name', 'help_issue_category', ['name'], unique=False)
    op.create_table('record_sms_send',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='操作人'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='发送状态'),
    sa.Column('content', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='发送内容'),
    sa.Column('telephone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=11), nullable=False, comment='目标手机号'),
    sa.Column('desc', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='失败描述'),
    sa.Column('scene', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='发送场景'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='record_sms_send_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='短信发送记录表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='短信发送记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_user',
    sa.Column('avatar', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=True, comment='头像'),
    sa.Column('telephone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=11), nullable=False, comment='手机号'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='邮箱地址'),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='姓名'),
    sa.Column('nickname', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='昵称'),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='密码'),
    sa.Column('gender', mysql.VARCHAR(collation='utf8mb4_general_ci', length=8), nullable=True, comment='性别'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否可用'),
    sa.Column('is_reset_password', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已经重置密码，没有重置的，登陆系统后必须重置密码'),
    sa.Column('last_ip', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='最后一次登录IP'),
    sa.Column('last_login', mysql.DATETIME(), nullable=True, comment='最近一次登录时间'),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否为工作人员'),
    sa.Column('wx_server_openid', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='服务端微信平台openid'),
    sa.Column('is_wx_server_openid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否已有服务端微信平台openid'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='用户表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_auth_user_telephone', 'auth_user', ['telephone'], unique=False)
    op.create_index('ix_auth_user_name', 'auth_user', ['name'], unique=False)
    op.create_table('auth_dept',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='部门名称'),
    sa.Column('dept_key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='部门标识'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True, comment='显示排序'),
    sa.Column('desc', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='描述'),
    sa.Column('owner', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='负责人'),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='联系电话'),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='邮箱'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='上级部门'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['auth_dept.id'], name='auth_dept_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='部门表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='部门表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_auth_dept_name', 'auth_dept', ['name'], unique=False)
    op.create_index('ix_auth_dept_dept_key', 'auth_dept', ['dept_key'], unique=False)
    op.create_table('auth_role_depts',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['auth_dept.id'], name='auth_role_depts_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], name='auth_role_depts_ibfk_2', ondelete='CASCADE'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('resource_images',
    sa.Column('filename', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='原图片名称'),
    sa.Column('image_url', mysql.VARCHAR(collation='utf8mb4_general_ci', length=500), nullable=False, comment='图片链接'),
    sa.Column('create_user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['create_user_id'], ['auth_user.id'], name='resource_images_ibfk_1', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='图片素材表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='图片素材表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('system_settings',
    sa.Column('config_label', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='配置表标签'),
    sa.Column('config_key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='配置表键'),
    sa.Column('config_value', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='配置表内容'),
    sa.Column('remark', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='备注信息'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('tab_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联tab标签'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['tab_id'], ['system_settings_tab.id'], name='system_settings_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='系统配置表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_system_settings_config_key', 'system_settings', ['config_key'], unique=True)
    op.create_table('auth_role',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='名称'),
    sa.Column('role_key', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='权限字符'),
    sa.Column('data_range', mysql.INTEGER(), autoincrement=False, nullable=False, comment='数据权限范围'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=True, comment='排序'),
    sa.Column('desc', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='描述'),
    sa.Column('is_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否为超级角色'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='角色表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_auth_role_role_key', 'auth_role', ['role_key'], unique=False)
    op.create_index('ix_auth_role_name', 'auth_role', ['name'], unique=False)
    op.create_table('system_settings_tab',
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='标题'),
    sa.Column('classify', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='分类键'),
    sa.Column('tab_label', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='tab标题'),
    sa.Column('tab_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='tab标识符'),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否隐藏'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置分类表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='系统配置分类表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_system_settings_tab_tab_name', 'system_settings_tab', ['tab_name'], unique=True)
    op.create_index('ix_system_settings_tab_classify', 'system_settings_tab', ['classify'], unique=False)
    op.create_table('record_login',
    sa.Column('telephone', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='手机号'),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否登录成功'),
    sa.Column('platform', mysql.VARCHAR(collation='utf8mb4_general_ci', length=8), nullable=False, comment='登陆平台'),
    sa.Column('login_method', mysql.VARCHAR(collation='utf8mb4_general_ci', length=8), nullable=False, comment='认证方式'),
    sa.Column('ip', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='登陆地址'),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='登陆地点'),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='国家'),
    sa.Column('province', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='县'),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='城市'),
    sa.Column('county', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='区/县'),
    sa.Column('operator', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='运营商'),
    sa.Column('postal_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='邮政编码'),
    sa.Column('area_code', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='地区区号'),
    sa.Column('browser', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='浏览器'),
    sa.Column('system', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='操作系统'),
    sa.Column('response', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='响应信息'),
    sa.Column('request', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=True, comment='请求信息'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.PrimaryKeyConstraint('id'),
    comment='登录记录表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='登录记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_record_login_telephone', 'record_login', ['telephone'], unique=False)
    op.create_table('auth_menu',
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False, comment='名称'),
    sa.Column('icon', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='菜单图标'),
    sa.Column('redirect', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True, comment='重定向地址'),
    sa.Column('component', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True, comment='前端组件地址'),
    sa.Column('path', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='前端路由地址'),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否禁用'),
    sa.Column('hidden', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否隐藏'),
    sa.Column('order', mysql.INTEGER(), autoincrement=False, nullable=False, comment='排序'),
    sa.Column('menu_type', mysql.VARCHAR(collation='utf8mb4_general_ci', length=8), nullable=False, comment='菜单类型'),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True, comment='父菜单'),
    sa.Column('perms', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True, comment='权限标识'),
    sa.Column('noCache', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='如果设置为true，则不会被 <keep-alive> 缓存(默认 false)'),
    sa.Column('breadcrumb', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='如果设置为false，则不会在breadcrumb面包屑中显示(默认 true)'),
    sa.Column('affix', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='如果设置为true，则会一直固定在tag项中(默认 false)'),
    sa.Column('noTagsView', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='如果设置为true，则不会出现在tag中(默认 false)'),
    sa.Column('canTo', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='设置为true即使hidden为true，也依然可以进行路由跳转(默认 false)'),
    sa.Column('alwaysShow', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='\n            当你一个路由下面的 children 声明的路由大于1个时，自动会变成嵌套的模式，\n            只有一个时，会将那个子路由当做根路由显示在侧边栏，若你想不管路由下面的 children 声明的个数都显示你的根路由，\n            你可以设置 alwaysShow: true，这样它就会忽略之前定义的规则，一直显示根路由(默认 true)\n        '),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['parent_id'], ['auth_menu.id'], name='auth_menu_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='菜单表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='菜单表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_auth_menu_perms', 'auth_menu', ['perms'], unique=False)
    op.create_table('help_issue',
    sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='类别'),
    sa.Column('title', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False, comment='标题'),
    sa.Column('content', mysql.TEXT(collation='utf8mb4_general_ci'), nullable=False, comment='内容'),
    sa.Column('view_number', mysql.INTEGER(), autoincrement=False, nullable=False, comment='查看次数'),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否可见'),
    sa.Column('create_user_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='创建人'),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('create_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_datetime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('delete_datetime', mysql.DATETIME(), nullable=True, comment='删除时间'),
    sa.Column('is_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False, comment='是否软删除'),
    sa.ForeignKeyConstraint(['category_id'], ['help_issue_category.id'], name='help_issue_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['create_user_id'], ['auth_user.id'], name='help_issue_ibfk_2', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='常见问题记录表',
    mysql_collate='utf8mb4_general_ci',
    mysql_comment='常见问题记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_help_issue_title', 'help_issue', ['title'], unique=False)
    op.create_table('auth_user_roles',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], name='auth_user_roles_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_roles_ibfk_2', ondelete='CASCADE'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_role_menus',
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('menu_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['menu_id'], ['auth_menu.id'], name='auth_role_menus_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['auth_role.id'], name='auth_role_menus_ibfk_2', ondelete='CASCADE'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_user_depts',
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dept_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['auth_dept.id'], name='auth_user_depts_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_depts_ibfk_2', ondelete='CASCADE'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
