"""3.12.1

Revision ID: f480d150dd84
Revises: 1e6e78c3854e
Create Date: 2025-07-11 22:59:58.442179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f480d150dd84'
down_revision = '1e6e78c3854e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
